version: '3'
services:

  postgres:
    build:
      context: ./docker
      dockerfile: postgres.dockerfile
    ports:
      - "54320:5432"
    environment:
      - POSTGRES_DB=miapp
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbpassword

  php7:
    build:
      context: ./docker
      dockerfile: php7.dockerfile
    volumes:
      - ./:/var/www
    working_dir: /var/www
    links:
      - postgres
    environment:
      - DB_CONNECTION=pgsql
      - DB_PORT=5432
      - DB_HOST=postgres
      - DB_DATABASE=miapp
      - DB_USERNAME=dbuser
      - DB_PASSWORD=dbpassword

  nginx:
    build:
      context: ./docker
      dockerfile: nginx.dockerfile
    volumes:
      - ./:/var/www
    working_dir: /var/www
    ports:
      - "8080:80"
    links:
      - php7
    command: [nginx-debug, '-g', 'daemon off;']