version: '3'
services:

  web:
    build:
      context: ./
      dockerfile: web.dockerfile
    volumes:
          - ./:/var/www
    working_dir: /var/www
    ports:
      - "8080:80"
    links:
      - app
    command: [nginx-debug, '-g', 'daemon off;']

  app:
    build:
      context: ./
      dockerfile: app.dockerfile
    volumes:
      - ./:/var/www
    working_dir: /var/www
    environment:
      - DB_PORT=3306
      - DB_HOST=database