version: '3'
services:

  nginx:
    build:
      context: ./
      dockerfile: docker/nginx.dockerfile
    volumes:
          - ./:/var/www
    working_dir: /var/www
    ports:
      - "8080:80"
    links:
      - php7
    command: [nginx-debug, '-g', 'daemon off;']

  php7:
    build:
      context: ./
      dockerfile: docker/php7.dockerfile
    volumes:
      - ./:/var/www
    working_dir: /var/www
    environment:
      - DB_PORT=3306
      - DB_HOST=database